### ISSUE TITLE
I can't go get this library undefined: identitytoolkit in identitytoolkit.UserInfo

### ISSUE THREAD

**Issue by salismt** [acoshift/go-firebase-admin#3]
I can't go get this library 
go get github.com/acoshift/go-firebase-admin
# github.com/acoshift/go-firebase-admin
github.com/acoshift/go-firebase-admin/api.go:42: undefined: identitytoolkit in identitytoolkit.UserInfo
github.com/acoshift/go-firebase-admin/api.go:58: undefined: identitytoolkit in identitytoolkit.UserInfo
github.com/acoshift/go-firebase-admin/api.go:66: undefined: identitytoolkit in identitytoolkit.UserInfoProviderUserInfo
github.com/acoshift/go-firebase-admin/api.go:76: undefined: identitytoolkit in identitytoolkit.UserInfoProviderUserInfo
github.com/acoshift/go-firebase-admin/auth.go:21: undefined: identitytoolkit in identitytoolkit.Service

**Comment by acoshift** [comment]
can you try `go get -u google.golang.org/api/identitytoolkit/v3` first ?
not sure why go get not get identitytoolkit first.
