### ISSUE TITLE
custom claims return nil

### ISSUE THREAD

**Issue by wildan2711** [acoshift/go-firebase-admin#43]
I have a custom claim with a struct for example:
```
type UserClaims struct {
    ID string `json:"id"`
}
```
and created a custom token using:
```
claims := UserClaims{ID: "5adfa5fd5a5"}
token, err := firebase.Auth().CreateCustomToken(uid, claims)
```
I send the token to the client (web), and it's used in the client app to sign in to firebase where it generates an `access_token`. The client uses the `Authorization` HTTP header to send requests to our Golang server app, where we use a middleware to extract the claims using `firebase.Auth().VerifyIDToken`. From that we can extract the claims, for example:

`&{https://securetoken.google.com/app 4ee4dFIo9ZZpjMBdiaEk8PyHQKg1 app 1504321776 1504325376 4ee4dFIo9ZZpjMBdiaEk8FSAAg1 <nil>}`

As you can see, the `Claims` is nil. 
Help is urgently needed, thank you very much..

**Comment by acoshift** [comment]
Hi,
firebase.Auth().currentUser.getIdToken() in client library not include claims in its body.
You can try test your access token in https://jwt.io

**Comment by wildan2711** [comment]
Thank you for pointing to https://jwt.io !

I was able to resolve my claims using that, it looks something like this:
```
{
  "iss": "https://securetoken.google.com/app",
  "name": "wildancok",
  "id": "60b664d7-9fa6-4c87-b412-b61db20542414",
  "aud": "app",
  "auth_time": 1504352839,
  "user_id": "4ee4daIofZZpjMBdiaEk8PyONAg1",
  "sub": "4ee4dsdo9ZZpjMBdiaEk8PyONAg1",
  "iat": 1504352839,
  "exp": 1504356439,
  "email": "email@gmail.com",
  "email_verified": false,
  "phone_number": "+1111111111",
  "firebase": {
    "identities": {
      "phone": [
        "+1111111111111"
      ],
      "email": [
        "email@gmail.com"
      ]
    },
    "sign_in_provider": "custom"
  }
}
```
I only need the `id` field. It seems the claims became into one struct containing all the custom fields. So I modified your `firebase.Claims` struct into this:
```
type Claims struct {
	Issuer    string      `json:"iss,omitempty"`
	Subject   string      `json:"sub,omitempty"`
	Audience  string      `json:"aud,omitempty"`
	IssuedAt  int64       `json:"iat,omitempty"`
	ExpiresAt int64       `json:"exp,omitempty"`
	UserID    string      `json:"uid,omitempty"`
	ID        string      `json:"id,omitempty"`
	Claims    interface{} `json:"claims,omitempty"`
}
```
Then my tests passed! So how would I go about providing a custom claim struct for token verification? Because whenever I update dependencies using `dep` it would revert my changes to this library.

Thank you very much!

**Comment by wildan2711** [comment]
I was expecting an answer on "how would I go about providing a custom claim struct for token verification? ",

**Comment by acoshift** [comment]
Yes!, I'll working on this tonight.
and maybe change `type Claims struct {` into `type Token struct {`

**Comment by acoshift** [comment]
Not sure why you need custom claims when verify id token, because firebase access token has its own structure.
Maybe I just add more fields to hold all access token data.

**Comment by wildan2711** [comment]
hmm.. So what is the point of creating a custom token with additional claims? What is the use case of additional claims?

**Comment by acoshift** [comment]
custom token is use for sign in on client (browser) to talk with security rules in firebase database.
see https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library

**Comment by acoshift** [comment]
IMO, I very sure that when you sign in with custom token, firebase store custom token claims on their server.
btw, you CAN NOT use token from create custom token in verify id token, because It use difference claims structure.

**Comment by wildan2711** [comment]
Okay thank you for the clarification and help. I had different ideas in using the custom token than the official firebase docs you just showed. Maybe I just fork your library just for my use case. 

Thank you once again, and sorry for my misunderstanding..
