### ISSUE TITLE
Https request issue in App Engine

### ISSUE THREAD

**Issue by jhbae200** [acoshift/go-firebase-admin#46]
When fetching a public-key from auth.VerifyIDToken, it was a problem on the app Engine.
https://cloud.google.com/appengine/docs/standard/go/issue-requests#issuing_an_https_request

My solution is to change http.DefaultClient before calling VerifyIdToken.
```
http.DefaultClient = urlfetch.Client(request)
token, err := fbAuth.VerifyIDToken(rtoken)
```
Is there a better way than this?

**Comment by acoshift** [comment]
Hi,
Can you try on app-option branch ?
and init firebase app with `google.golang.org/api/option` like this
```go
firebase.InitializeApp(ctx, firebase.AppOptions({...}), option.WithCredentialsFile("your-service-account.json"), option.WithHTTPClient(urlfetch.Client(ctx)))
```

**Comment by jhbae200** [comment]
Nice!
Thanks:)
