### ISSUE TITLE
Document AppOptions.DatabaseURL is required

### ISSUE THREAD

**Issue by james2doyle** [acoshift/go-firebase-admin#49]
I did a copy/paste of one of the examples from the README. I was getting the following error:

```
panic: Post /endpoint-path.json: unsupported protocol scheme ""
```

It looks like the base URL for the database is not being set or it doesn't handle a case where it is missing.

Adding `DatabaseURL` to `firebase.AppOptions` fixed the issue.

I can update the README if this is the case. Is that correct?

**Comment by acoshift** [comment]
Yes, it’s required for using Firebase Database
